### ISSUE TITLE
not worked

### ISSUE THREAD

**Issue by rusvo** [barreleye-labs/barreleye#94]
with my privatekey

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x73babc]

goroutine 1 [running]:
main.main()
        /barreleye/main.go:36 +0x43c

**Comment by rusvo** [comment]
i create account, and use private key on scrypt, but it not worked. When i set your private key c4e0f3f39c5438d2f7*****************************, scrypt worked

**Comment by k930503** [comment]
hello. 
 Currently, there are differences between websites and nodes in the method of generating private keys. If you need a private key to run the node, uncomment main.go and use hexPrivateKey.

 Thank you so much for your interest in our Barreleye project. Could I ask the reason and purpose of running the Barreleye node?
<img width="672" alt="hexPrivateKey" src="https://github.com/barreleye-labs/barreleye/assets/48827393/c0146865-d1b9-455d-b0fc-cdbfe06b5ee8">

**Comment by rusvo** [comment]
interesting project) 
im uncomment main.go, how i can get private key? run main.go?

**Comment by k930503** [comment]
That's right.
Uncomment it and enter the command 'make barreleye'.
Then obtain the printed hexPrivateKey.

**Comment by rusvo** [comment]
make barreleye
make: 'barreleye' is up to date.

**Comment by rusvo** [comment]
can you make a discord? i have little community, we want help you to test your project!

**Comment by rusvo** [comment]
root@DESKTOP-OF08MGH:/home/rusvo/barreleye# make barreleye
go build -o ./bin/barreleye
./main.go:28:19: undefined: hex
./main.go:28:38: undefined: crypto
./main.go:29:20: undefined: crypto
./main.go:31:2: undefined: fmt
make: *** [Makefile:2: build] Error 1

**Comment by rusvo** [comment]
![image](https://github.com/barreleye-labs/barreleye/assets/51915350/6c82c307-1b65-469b-8a36-b924b13fa6c4)

**Comment by k930503** [comment]
Install and import the relevant packages before proceeding.
I plan to open a Discord later. Let's communicate here as much as possible so that our communication may be helpful to others as well.

**Comment by rusvo** [comment]
import "crypto"
import "hex"
import "fmt"
add to main.go
go run main.go
main.go:4:8: package hex is not in std (/usr/local/go/src/hex)

**Comment by k930503** [comment]
The imports needed for main.go are these.
import (
	"encoding/hex"
	"fmt"
	"github.com/barreleye-labs/barreleye/common"
	"github.com/barreleye-labs/barreleye/core/types"
	"github.com/ethereum/go-ethereum/crypto"
	"log"
	"strings"
	"time"

	"github.com/barreleye-labs/barreleye/node"
)

And you must use 'make barreleye' command, not 'go run main.go' command.
Just in case, match the go version as well. The barreleye project is go version 1.22.

**Comment by rusvo** [comment]
Thx its worked!

**Comment by rusvo** [comment]
if i create self genesis node, and connect to genesis with normal node, i make new chain? and on barrelscan i not see my balance from my chain ?

**Comment by rusvo** [comment]
![image](https://github.com/barreleye-labs/barreleye/assets/51915350/b2a5b326-af27-47f5-b1d2-c952283eebfe)

**Comment by k930503** [comment]
Yes, then it becomes your private blockchain. At https://barreleyescan.com, you can only view accounts on the main network.

**Comment by rusvo** [comment]
i cant connect to address from example, which address connect to yours three nodes?
barrelscan.com:4000 (4001, 4002) not connect

**Comment by k930503** [comment]
Running on mainnet
Are you saying you want to connect to three nodes?
Since the current nodes are running in a cloud environment, to eliminate network costs, three nodes are running in the same region and external access is blocked.

**Comment by rusvo** [comment]
Why was this project created?
Can I connect to you and mine coins?
Are you planning to list on an exchange?
Why is there no transfer fee in your network?

**Comment by k930503** [comment]
We make it as a hobby.

Currently, the Barreleye project has too many tasks remaining. Even basic aspects such as efficient consensus and smart contract support have not been applied.

After getting the basics covered, we will apply something that will give Barreleye its unique competitive edge.

Our development team enjoys the project and plans to continue developing it. If we develop with the goal of listing on an exchange, our team may lose passion for the project.

 Listing on exchanges is something we will consider in the future when the need is felt after our project becomes competitive.

Since the current nodes are running in a cloud environment, we will not accept external nodes yet to reduce network costs.

Thank you for your interest in our project, and please continue to follow Barreleye's growth.
